# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 01:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctorId', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.CharField(max_length=20, unique=True)),
                ('cellphone', models.CharField(max_length=10)),
                ('officePhone', models.CharField(max_length=10)),
                ('userType', models.CharField(choices=[('admin', 'Administrator'), ('std', 'Standard'), ('lmtd', 'Limited')], default='std', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
