# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctorId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('document', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('cellphone', models.CharField(max_length=10)),
                ('officePhone', models.CharField(max_length=10)),
                ('userType', models.CharField(choices=[('admin', 'Administrator'), ('std', 'Standard'), ('lmtd', 'Limited')], default='std', max_length=5)),
            ],
        ),
    ]
